CREATE TABLE T_AVION(
Matricula VARCHAR(15) NOT NULL PRIMARY KEY,
Fabricante VARCHAR(45) NOT NULL,
Modelo VARCHAR(20) NOT NULL,
Capacidad INT NOT NULL,
Autonomia VARCHAR(10) NOT NULL
);

CREATE TABLE T_VUELO(
ID VARCHAR(20) NOT NULL PRIMARY KEY,
Matricula VARCHAR(15) NOT NULL,
AeropuertoOrigen VARCHAR(45) NOT NULL,
AeropuertoDestino VARCHAR(45) NOT NULL,
Fecha DATE NOT NULL,
CONSTRAINT T_VUELO_AVION
   FOREIGN KEY(Matricula) REFERENCES T_AVION(Matricula)
);


CREATE TABLE T_PASAJERO(
DNI CHAR(9) NOT NULL PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL,
Apellidos VARCHAR(30) NOT NULL,
Email VARCHAR(45) NOT NULL
);


CREATE TABLE T_TELEFONO(
Telefono VARCHAR(15) NOT NULL PRIMARY KEY,
DNIPasajero CHAR(9) NOT NULL,
CONSTRAINT T_PASAJERO_TELEFONO
   FOREIGN KEY(DNIPasajero) REFERENCES T_PASAJERO(DNI)
);



CREATE TABLE T_DISTRIBUCION(
DNIPasajero CHAR(9) NOT NULL,
IDVuelo VARCHAR(20) NOT NULL,
Asiento CHAR(3) NOT NULL,
Clase VARCHAR(15) NOT NULL,
CONSTRAINT T_PASAJERO1_VUELO1_DISTRIBUCION1
   FOREIGN KEY(DNIPasajero) REFERENCES T_PASAJERO(DNI),
CONSTRAINT T_PASAJERO2_VUELO2_DISTRIBUCION2
   FOREIGN KEY(IDVuelo) REFERENCES T_VUELO(ID)
);



CREATE TABLE T_CATEGORIA_PROFESIONAL(
Codigo VARCHAR(10) NOT NULL PRIMARY KEY,
Nombre VARCHAR(20)NOT NULL
);


CREATE TABLE T_PERSONAL(
ID VARCHAR(10) NOT NULL PRIMARY KEY,
CodigoTrabajador VARCHAR(10) NOT NULL,
Nombre VARCHAR(10) NOT NULL,
PrimerApellido VARCHAR(20) NOT NULL,
SegundoApellido VARCHAR(20) NULL,
CONSTRAINT T_PERSONAL_CATEGORIA_PROFESIONAL
   FOREIGN KEY(CodigoTrabajador) REFERENCES T_CATEGORIA_PROFESIONAL(Codigo) 
);


CREATE TABLE T_TELEFONO_PERSONAL(
Telefono VARCHAR(15) NOT NULL PRIMARY KEY,
IDTrabajador VARCHAR(10) NOT NULL,
CONSTRAINT T_PERSONAL_TELEFONO_PERSONAL
   FOREIGN KEY(IDTrabajador) REFERENCES T_PERSONAL(ID)
);


CREATE TABLE T_PUESTO(
IDTrabajador VARCHAR(10) NOT NULL,
IDVuelo VARCHAR(20) NOT NULL,
Puesto VARCHAR(20) NOT NULL,
CONSTRAINT PUESTO_PERSONAL
    FOREIGN KEY(IDTrabajador) REFERENCES T_PERSONAL(ID),
CONSTRAINT PUESTO_VUELO
    FOREIGN KEY(IDVuelo) REFERENCES T_VUELO(ID)
);







RENAME TABLE T_AVION TO T_AEROPLANO;


ALTER DATABASE compañia_aerea
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;


ALTER TABLE T_AEROPLANO
MODIFY Capacidad INT UNSIGNED CHECK (Capacidad <= 450);

ALTER TABLE T_AEROPLANO
MODIFY Autonomia INT UNSIGNED CHECK (Autonomia <= 48);


ALTER TABLE T_AEROPLANO
ADD COLUMN Autonomia_opcional INT UNSIGNED;


ALTER TABLE T_PERSONAL
MODIFY SegundoApellido VARCHAR(255);


CREATE TABLE T_TipoClase (
    tipo_id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_tipo VARCHAR(50)
);


ALTER TABLE T_PASAJERO
ADD COLUMN tipo_id INT,
ADD FOREIGN KEY (tipo_id) REFERENCES T_TipoClase(tipo_id);


ALTER TABLE PASAJEROS
ADD COLUMN asiento INT CHECK (asiento > 0);





